source "https://supermarket.chef.io"

cookbook 'iis'
cookbook 'ms_dotnet'
cookbook 'chocolatey'
cookbook 'webpi'
cookbook 'windows'
cookbook 'sql_server'
cookbook 'seven_zip'
cookbook 'ntp'
cookbook 'docker'
cookbook 'windows_ad'
